DAQ-6510:
  serial-interface:
    port: /dev/ttyUSB1
    baudrate: 115200
    bytesize: 8
    stopbits: 1
    parity: N
    timeout: 2.0
  settings:
    nplc: 1  # nplc of all DC measurements, reduce this for higher sampling rates!
    lsync: True  # line sync for all channels
    ocom: True  # offset compensation for all channels
    azer: False  # automatic zeroing for all channels
    adel: True  # automatic delay for all channels
    internal-cold-junction: False  # if False: use 0.0°C
  channels:
    201: 
      type: dcv
      tab-name: Current
      range: 10  # V (optional)
      sensor-id: rogowski_PEM_300A
      factor: 50 # Ampere / Volt
      unit: A
      
Heizer:
  Schnittstelle:
    com:      '/dev/ttyUSB0'   
    bd:       9600              # Emulation: 19200 (8N1) - Eurotherm/IKA: 9600 (7E1)
    parity:   'E'
    stopbits: 1
    bytesize: 7
  Auswahl:
    String: IKA              # IKA = IKA Heizplatte, Eurotherm = Eurotherm
